// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/spidernet-io/rocktemplate/pkg/k8s/client/clientset/versioned/typed/rocktemplate.spidernet.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeRocktemplateV1 struct {
	*testing.Fake
}

func (c *FakeRocktemplateV1) Mybooks() v1.MybookInterface {
	return &FakeMybooks{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeRocktemplateV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
