// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/koffloader-io/koffloader/pkg/k8s/client/clientset/versioned/typed/koffloader.koffloader.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakekoffloaderV1 struct {
	*testing.Fake
}

func (c *FakekoffloaderV1) Kclusters() v1.KclusterInterface {
	return &FakeKclusters{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakekoffloaderV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
