// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	koffloaderspidernetiov1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// Fakekclusters implements kclusterInterface
type Fakekclusters struct {
	Fake *FakekoffloaderV1
}

var kclustersResource = schema.GroupVersionResource{Group: "koffloader.koffloader.io", Version: "v1", Resource: "kclusters"}

var kclustersKind = schema.GroupVersionKind{Group: "koffloader.koffloader.io", Version: "v1", Kind: "kcluster"}

// Get takes name of the kcluster, and returns the corresponding kcluster object, and an error if there is any.
func (c *Fakekclusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *koffloaderspidernetiov1.kcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kclustersResource, name), &koffloaderspidernetiov1.kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderspidernetiov1.kcluster), err
}

// List takes label and field selectors, and returns the list of kclusters that match those selectors.
func (c *Fakekclusters) List(ctx context.Context, opts v1.ListOptions) (result *koffloaderspidernetiov1.kclusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kclustersResource, kclustersKind, opts), &koffloaderspidernetiov1.kclusterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &koffloaderspidernetiov1.kclusterList{ListMeta: obj.(*koffloaderspidernetiov1.kclusterList).ListMeta}
	for _, item := range obj.(*koffloaderspidernetiov1.kclusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kclusters.
func (c *Fakekclusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kclustersResource, opts))
}

// Create takes the representation of a kcluster and creates it.  Returns the server's representation of the kcluster, and an error, if there is any.
func (c *Fakekclusters) Create(ctx context.Context, kcluster *koffloaderspidernetiov1.kcluster, opts v1.CreateOptions) (result *koffloaderspidernetiov1.kcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kclustersResource, kcluster), &koffloaderspidernetiov1.kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderspidernetiov1.kcluster), err
}

// Update takes the representation of a kcluster and updates it. Returns the server's representation of the kcluster, and an error, if there is any.
func (c *Fakekclusters) Update(ctx context.Context, kcluster *koffloaderspidernetiov1.kcluster, opts v1.UpdateOptions) (result *koffloaderspidernetiov1.kcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kclustersResource, kcluster), &koffloaderspidernetiov1.kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderspidernetiov1.kcluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *Fakekclusters) UpdateStatus(ctx context.Context, kcluster *koffloaderspidernetiov1.kcluster, opts v1.UpdateOptions) (*koffloaderspidernetiov1.kcluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kclustersResource, "status", kcluster), &koffloaderspidernetiov1.kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderspidernetiov1.kcluster), err
}

// Delete takes name of the kcluster and deletes it. Returns an error if one occurs.
func (c *Fakekclusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(kclustersResource, name, opts), &koffloaderspidernetiov1.kcluster{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *Fakekclusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kclustersResource, listOpts)

	_, err := c.Fake.Invokes(action, &koffloaderspidernetiov1.kclusterList{})
	return err
}

// Patch applies the patch and returns the patched kcluster.
func (c *Fakekclusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *koffloaderspidernetiov1.kcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kclustersResource, name, pt, data, subresources...), &koffloaderspidernetiov1.kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderspidernetiov1.kcluster), err
}
