// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// kclusterListerExpansion allows custom methods to be added to
// kclusterLister.
type kclusterListerExpansion interface{}
