// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/spidernet-io/rocktemplate/pkg/k8s/apis/rocktemplate.spidernet.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MybookLister helps list Mybooks.
// All objects returned here must be treated as read-only.
type MybookLister interface {
	// List lists all Mybooks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Mybook, err error)
	// Get retrieves the Mybook from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.Mybook, error)
	MybookListerExpansion
}

// mybookLister implements the MybookLister interface.
type mybookLister struct {
	indexer cache.Indexer
}

// NewMybookLister returns a new MybookLister.
func NewMybookLister(indexer cache.Indexer) MybookLister {
	return &mybookLister{indexer: indexer}
}

// List lists all Mybooks in the indexer.
func (s *mybookLister) List(selector labels.Selector) (ret []*v1.Mybook, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Mybook))
	})
	return ret, err
}

// Get retrieves the Mybook from the index for a given name.
func (s *mybookLister) Get(name string) (*v1.Mybook, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("mybook"), name)
	}
	return obj.(*v1.Mybook), nil
}
