//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumServiceFeature) DeepCopyInto(out *CiliumServiceFeature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumServiceFeature.
func (in *CiliumServiceFeature) DeepCopy() *CiliumServiceFeature {
	if in == nil {
		return nil
	}
	out := new(CiliumServiceFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectorType) DeepCopyInto(out *ClusterConnectorType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectorType.
func (in *ClusterConnectorType) DeepCopy() *ClusterConnectorType {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportService) DeepCopyInto(out *ExportService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportService.
func (in *ExportService) DeepCopy() *ExportService {
	if in == nil {
		return nil
	}
	out := new(ExportService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCluster) DeepCopyInto(out *KCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCluster.
func (in *KCluster) DeepCopy() *KCluster {
	if in == nil {
		return nil
	}
	out := new(KCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KClusterGroup) DeepCopyInto(out *KClusterGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KClusterGroup.
func (in *KClusterGroup) DeepCopy() *KClusterGroup {
	if in == nil {
		return nil
	}
	out := new(KClusterGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KClusterGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KClusterGroupList) DeepCopyInto(out *KClusterGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KClusterGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KClusterGroupList.
func (in *KClusterGroupList) DeepCopy() *KClusterGroupList {
	if in == nil {
		return nil
	}
	out := new(KClusterGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KClusterGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KClusterGroupSpec) DeepCopyInto(out *KClusterGroupSpec) {
	*out = *in
	if in.ClusterConnectorType != nil {
		in, out := &in.ClusterConnectorType, &out.ClusterConnectorType
		*out = new(string)
		**out = **in
	}
	if in.KClusterSelector != nil {
		in, out := &in.KClusterSelector, &out.KClusterSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KClusterGroupSpec.
func (in *KClusterGroupSpec) DeepCopy() *KClusterGroupSpec {
	if in == nil {
		return nil
	}
	out := new(KClusterGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KClusterGroupStatus) DeepCopyInto(out *KClusterGroupStatus) {
	*out = *in
	if in.MatchKCluster != nil {
		in, out := &in.MatchKCluster, &out.MatchKCluster
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KClusterGroupStatus.
func (in *KClusterGroupStatus) DeepCopy() *KClusterGroupStatus {
	if in == nil {
		return nil
	}
	out := new(KClusterGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KClusterList) DeepCopyInto(out *KClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KClusterList.
func (in *KClusterList) DeepCopy() *KClusterList {
	if in == nil {
		return nil
	}
	out := new(KClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KClusterSpec) DeepCopyInto(out *KClusterSpec) {
	*out = *in
	if in.ClusterConnector != nil {
		in, out := &in.ClusterConnector, &out.ClusterConnector
		*out = new(ClusterConnectorType)
		**out = **in
	}
	if in.KubeConfig != nil {
		in, out := &in.KubeConfig, &out.KubeConfig
		*out = new(Kubeconfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KClusterSpec.
func (in *KClusterSpec) DeepCopy() *KClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KClusterStatus) DeepCopyInto(out *KClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KClusterStatus.
func (in *KClusterStatus) DeepCopy() *KClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubeconfig) DeepCopyInto(out *Kubeconfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubeconfig.
func (in *Kubeconfig) DeepCopy() *Kubeconfig {
	if in == nil {
		return nil
	}
	out := new(Kubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceExportPolicy) DeepCopyInto(out *ServiceExportPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceExportPolicy.
func (in *ServiceExportPolicy) DeepCopy() *ServiceExportPolicy {
	if in == nil {
		return nil
	}
	out := new(ServiceExportPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceExportPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceExportPolicyList) DeepCopyInto(out *ServiceExportPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceExportPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceExportPolicyList.
func (in *ServiceExportPolicyList) DeepCopy() *ServiceExportPolicyList {
	if in == nil {
		return nil
	}
	out := new(ServiceExportPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceExportPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceExportPolicySpec) DeepCopyInto(out *ServiceExportPolicySpec) {
	*out = *in
	if in.CiliumServiceFeature != nil {
		in, out := &in.CiliumServiceFeature, &out.CiliumServiceFeature
		*out = new(CiliumServiceFeature)
		**out = **in
	}
	if in.ServiceSelector != nil {
		in, out := &in.ServiceSelector, &out.ServiceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KClusterSelector != nil {
		in, out := &in.KClusterSelector, &out.KClusterSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceExportPolicySpec.
func (in *ServiceExportPolicySpec) DeepCopy() *ServiceExportPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceExportPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceExportPolicyStatus) DeepCopyInto(out *ServiceExportPolicyStatus) {
	*out = *in
	if in.MatchKCluster != nil {
		in, out := &in.MatchKCluster, &out.MatchKCluster
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchService != nil {
		in, out := &in.MatchService, &out.MatchService
		*out = make([]ExportService, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceExportPolicyStatus.
func (in *ServiceExportPolicyStatus) DeepCopy() *ServiceExportPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceExportPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
