// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	koffloaderkoffloaderiov1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1"
	versioned "github.com/koffloader-io/koffloader/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/koffloader-io/koffloader/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/koffloader-io/koffloader/pkg/k8s/client/listers/koffloader.koffloader.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KclusterInformer provides access to a shared informer and lister for
// Kclusters.
type KclusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KclusterLister
}

type kclusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewKclusterInformer constructs a new informer for Kcluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKclusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKclusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredKclusterInformer constructs a new informer for Kcluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKclusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KoffloaderV1().Kclusters().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KoffloaderV1().Kclusters().Watch(context.TODO(), options)
			},
		},
		&koffloaderkoffloaderiov1.Kcluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *kclusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKclusterInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kclusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&koffloaderkoffloaderiov1.Kcluster{}, f.defaultInformer)
}

func (f *kclusterInformer) Lister() v1.KclusterLister {
	return v1.NewKclusterLister(f.Informer().GetIndexer())
}
