
## @section Global parameters
##
global:
  ## @param global.imageRegistryOverride Global Docker image registry
  imageRegistryOverride: ""

  ## @param global.imageTagOverride Global Docker image tag
  imageTagOverride: ""

  ## @param global.name instance name
  ## default rocktemplate
  name: "rocktemplate"

  ## @param global.clusterDnsDomain cluster dns domain
  clusterDnsDomain: "cluster.local"

  ## @param global.commonAnnotations Annotations to add to all deployed objects
  commonAnnotations: {}

  ## @param global.commonLabels Labels to add to all deployed objects
  commonLabels: {}
  #  label1: v1
  #  labele: v2

  ## @param global.configName the configmap name
  configName: "rocktemplate"

## @section feature parameters
feature:
  ## @param feature.enableIPv4 enable ipv4
  enableIPv4: true

  ## @param feature.enableIPv6 enable ipv6
  enableIPv6: false

## @section rocktemplateAgent parameters
##
rocktemplateAgent:
  ## @param rocktemplateAgent.name the rocktemplateAgent name
  name: "rocktemplate-agent"

  ## @param rocktemplateAgent.cmdBinName the binary name of rocktemplateAgent
  cmdBinName: "/usr/bin/agent"

  ## @param rocktemplateAgent.hostnetwork enable hostnetwork mode of rocktemplateAgent pod
  hostnetwork: true

  image:
    ## @param rocktemplateAgent.image.registry the image registry of rocktemplateAgent
    registry: ghcr.io

    ## @param rocktemplateAgent.image.repository the image repository of rocktemplateAgent
    repository: spidernet-io/rocktemplate-agent

    ## @param rocktemplateAgent.image.pullPolicy the image pullPolicy of rocktemplateAgent
    pullPolicy: IfNotPresent

    ## @param rocktemplateAgent.image.digest the image digest of rocktemplateAgent, which takes preference over tag
    digest: ""

    ## @param rocktemplateAgent.image.tag the image tag of rocktemplateAgent, overrides the image tag whose default is the chart appVersion.
    tag: ""

    ## @param rocktemplateAgent.image.imagePullSecrets the image imagePullSecrets of rocktemplateAgent
    imagePullSecrets: []
    # - name: "image-pull-secret"

  ## @skip rocktemplateAgent.nodeSelector.kubernetes.io/os
  nodeSelector:
    kubernetes.io/os: linux

  serviceAccount:
    ## @param rocktemplateAgent.serviceAccount.create create the service account for the rocktemplateAgent
    create: true
    ## @param rocktemplateAgent.serviceAccount.annotations the annotations of rocktemplateAgent service account
    annotations: {}

  ## @skip rocktemplateAgent.updateStrategy.rollingUpdate.maxUnavailable
  ## @skip rocktemplateAgent.updateStrategy.type
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate

  service:
    ## @param rocktemplateAgent.service.annotations the annotations for rocktemplateAgent service
    annotations: {}
    ## @param rocktemplateAgent.service.type the type for rocktemplateAgent service
    type: ClusterIP

  ## @skip rocktemplateAgent.tolerations
  tolerations:
    - operator: Exists

  ## @param rocktemplateAgent.priorityClassName the priority Class Name for rocktemplateAgent
  priorityClassName: "system-node-critical"

  ## @param rocktemplateAgent.affinity the affinity of rocktemplateAgent
  affinity: {}

  ## @param rocktemplateAgent.extraArgs the additional arguments of rocktemplateAgent container
  extraArgs: []

  ## @param rocktemplateAgent.extraEnv the additional environment variables of rocktemplateAgent container
  extraEnv: []

  ## @param rocktemplateAgent.extraVolumes the additional volumes of rocktemplateAgent container
  extraVolumes: []

  ## @param rocktemplateAgent.extraVolumeMounts the additional hostPath mounts of rocktemplateAgent container
  extraVolumeMounts: []

  ## @param rocktemplateAgent.podAnnotations the additional annotations of rocktemplateAgent pod
  podAnnotations: {}

  ## @param rocktemplateAgent.podLabels the additional label of rocktemplateAgent pod
  podLabels: {}

  resources:
    ## @param rocktemplateAgent.resources.limits.cpu the cpu limit of rocktemplateAgent pod
    ## @param rocktemplateAgent.resources.limits.memory the memory limit of rocktemplateAgent pod
    ## @param rocktemplateAgent.resources.requests.cpu the cpu requests of rocktemplateAgent pod
    ## @param rocktemplateAgent.resources.requests.memory the memory requests of rocktemplateAgent pod
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

  ## @param rocktemplateAgent.securityContext the security Context of rocktemplateAgent pod
  securityContext: {}
  # runAsUser: 0

  httpServer:
    ## @param rocktemplateAgent.httpServer.port the http Port for rocktemplateAgent, for health checking
    port: 5710

    startupProbe:
      ## @param rocktemplateAgent.httpServer.startupProbe.failureThreshold the failure threshold of startup probe for rocktemplateAgent health checking
      failureThreshold: 60
      ## @param rocktemplateAgent.httpServer.startupProbe.periodSeconds the period seconds of startup probe for rocktemplateAgent health checking
      periodSeconds: 2

    livenessProbe:
      ## @param rocktemplateAgent.httpServer.livenessProbe.failureThreshold the failure threshold of startup probe for rocktemplateAgent health checking
      failureThreshold: 6
      ## @param rocktemplateAgent.httpServer.livenessProbe.periodSeconds the period seconds of startup probe for rocktemplateAgent health checking
      periodSeconds: 10

    readinessProbe:
      ## @param rocktemplateAgent.httpServer.readinessProbe.failureThreshold the failure threshold of startup probe for rocktemplateAgent health checking
      failureThreshold: 3
      ## @param rocktemplateAgent.httpServer.readinessProbe.periodSeconds the period seconds of startup probe for rocktemplateAgent health checking
      periodSeconds: 10

  prometheus:
    ## @param rocktemplateAgent.prometheus.enabled enable template agent to collect metrics
    enabled: false

    ## @param rocktemplateAgent.prometheus.port the metrics port of template agent
    port: 5711

    serviceMonitor:
      ## @param rocktemplateAgent.prometheus.serviceMonitor.install install serviceMonitor for template agent. This requires the prometheus CRDs to be available
      install: false

      ## @param rocktemplateAgent.prometheus.serviceMonitor.namespace the serviceMonitor namespace. Default to the namespace of helm instance
      namespace: ""

      ## @param rocktemplateAgent.prometheus.serviceMonitor.annotations the additional annotations of rocktemplateAgent serviceMonitor
      annotations: {}

      ## @param rocktemplateAgent.prometheus.serviceMonitor.labels the additional label of rocktemplateAgent serviceMonitor
      labels: {}

    prometheusRule:
      ## @param rocktemplateAgent.prometheus.prometheusRule.install install prometheusRule for template agent. This requires the prometheus CRDs to be available
      install: false

      ## @param rocktemplateAgent.prometheus.prometheusRule.namespace the prometheusRule namespace. Default to the namespace of helm instance
      namespace: ""

      ## @param rocktemplateAgent.prometheus.prometheusRule.annotations the additional annotations of rocktemplateAgent prometheusRule
      annotations: {}

      ## @param rocktemplateAgent.prometheus.prometheusRule.labels the additional label of rocktemplateAgent prometheusRule
      labels: {}

    grafanaDashboard:
      ## @param rocktemplateAgent.prometheus.grafanaDashboard.install install grafanaDashboard for template agent. This requires the prometheus CRDs to be available
      install: false

      ## @param rocktemplateAgent.prometheus.grafanaDashboard.namespace the grafanaDashboard namespace. Default to the namespace of helm instance
      namespace: ""

      ## @param rocktemplateAgent.prometheus.grafanaDashboard.annotations the additional annotations of rocktemplateAgent grafanaDashboard
      annotations: {}

      ## @param rocktemplateAgent.prometheus.grafanaDashboard.labels the additional label of rocktemplateAgent grafanaDashboard
      labels: {}

  debug:
    ## @param rocktemplateAgent.debug.logLevel the log level of template agent [debug, info, warn, error, fatal, panic]
    logLevel: "info"
    ## @param rocktemplateAgent.debug.gopsPort the gops port of template agent
    gopsPort: 5712

## @section rocktemplateController parameters
##
rocktemplateController:
  ## @param rocktemplateController.name the rocktemplateController name
  name: "rocktemplate-controller"

  ## @param rocktemplateController.replicas the replicas number of rocktemplateController pod
  replicas: 1

  ## @param rocktemplateController.binName the binName name of rocktemplateController
  cmdBinName: "/usr/bin/controller"

  ## @param rocktemplateController.hostnetwork enable hostnetwork mode of rocktemplateController pod. Notice, if no CNI available before template installation, must enable this
  hostnetwork: false

  image:
    ## @param rocktemplateController.image.registry the image registry of rocktemplateController
    registry: ghcr.io

    ## @param rocktemplateController.image.repository the image repository of rocktemplateController
    repository: spidernet-io/rocktemplate-controller

    ## @param rocktemplateController.image.pullPolicy the image pullPolicy of rocktemplateController
    pullPolicy: IfNotPresent

    ## @param rocktemplateController.image.digest the image digest of rocktemplateController, which takes preference over tag
    digest: ""

    ## @param rocktemplateController.image.tag the image tag of rocktemplateController, overrides the image tag whose default is the chart appVersion.
    tag: ""

    ## @param rocktemplateController.image.imagePullSecrets the image imagePullSecrets of rocktemplateController
    imagePullSecrets: []
    # - name: "image-pull-secret"

  ## @skip rocktemplateController.nodeSelector.kubernetes.io/os
  nodeSelector:
    kubernetes.io/os: linux

  serviceAccount:
    ## @param rocktemplateController.serviceAccount.create create the service account for the rocktemplateController
    create: true
    ## @param rocktemplateController.serviceAccount.annotations the annotations of rocktemplateController service account
    annotations: {}

  service:
    ## @param rocktemplateController.service.annotations the annotations for rocktemplateController service
    annotations: {}
    ## @param rocktemplateController.service.type the type for rocktemplateController service
    type: ClusterIP

  ## @skip rocktemplateController.tolerations
  tolerations:
    - operator: Exists

  ## @param rocktemplateController.priorityClassName the priority Class Name for rocktemplateController
  priorityClassName: "system-node-critical"

  ## @param rocktemplateController.affinity the affinity of rocktemplateController
  affinity: {}

  ## @param rocktemplateController.extraArgs the additional arguments of rocktemplateController container
  extraArgs: []

  ## @param rocktemplateController.extraEnv the additional environment variables of rocktemplateController container
  extraEnv: []

  ## @param rocktemplateController.extraVolumes the additional volumes of rocktemplateController container
  extraVolumes: []
    # - name: test-val
  #   mountPath: /host/tmp

  ## @param rocktemplateController.extraVolumeMounts the additional hostPath mounts of rocktemplateController container
  extraVolumeMounts: []
    # - name: test-val
  #   mountPath: /tmp

  ## @param rocktemplateController.podAnnotations the additional annotations of rocktemplateController pod
  podAnnotations: {}
  # test: 100

  ## @param rocktemplateController.podLabels the additional label of rocktemplateController pod
  podLabels: {}

  ## @param rocktemplateController.securityContext the security Context of rocktemplateController pod
  securityContext: {}
  # runAsUser: 0

  resources:
    ## @param rocktemplateController.resources.limits.cpu the cpu limit of rocktemplateController pod
    ## @param rocktemplateController.resources.limits.memory the memory limit of rocktemplateController pod
    ## @param rocktemplateController.resources.requests.cpu the cpu requests of rocktemplateController pod
    ## @param rocktemplateController.resources.requests.memory the memory requests of rocktemplateController pod
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

  podDisruptionBudget:
    ## @param rocktemplateController.podDisruptionBudget.enabled enable podDisruptionBudget for rocktemplateController pod
    enabled: false

    ## @param rocktemplateController.podDisruptionBudget.minAvailable minimum number/percentage of pods that should remain scheduled.
    minAvailable: 1

  httpServer:
    ## @param rocktemplateController.port the http Port for rocktemplateController, for health checking and http service
    port: 5720

    startupProbe:
      ## @param rocktemplateController.httpServer.startupProbe.failureThreshold the failure threshold of startup probe for rocktemplateController health checking
      failureThreshold: 30

      ## @param rocktemplateController.httpServer.startupProbe.periodSeconds the period seconds of startup probe for rocktemplateController health checking
      periodSeconds: 2

    livenessProbe:
      ## @param rocktemplateController.httpServer.livenessProbe.failureThreshold the failure threshold of startup probe for rocktemplateController health checking
      failureThreshold: 6

      ## @param rocktemplateController.httpServer.livenessProbe.periodSeconds the period seconds of startup probe for rocktemplateController health checking
      periodSeconds: 10

    readinessProbe:
      ## @param rocktemplateController.httpServer.readinessProbe.failureThreshold the failure threshold of startup probe for rocktemplateController health checking
      failureThreshold: 3

      ## @param rocktemplateController.httpServer.readinessProbe.periodSeconds the period seconds of startup probe for rocktemplateController health checking
      periodSeconds: 10

  ## @param rocktemplateController.webhookPort the http port for rocktemplateController webhook
  webhookPort: 5722

  prometheus:
    ## @param rocktemplateController.prometheus.enabled enable template Controller to collect metrics
    enabled: false

    ## @param rocktemplateController.prometheus.port the metrics port of template Controller
    port: 5721

    serviceMonitor:
      ## @param rocktemplateController.prometheus.serviceMonitor.install install serviceMonitor for template agent. This requires the prometheus CRDs to be available
      install: false

      ## @param rocktemplateController.prometheus.serviceMonitor.namespace the serviceMonitor namespace. Default to the namespace of helm instance
      namespace: ""

      ## @param rocktemplateController.prometheus.serviceMonitor.annotations the additional annotations of rocktemplateController serviceMonitor
      annotations: {}

      ## @param rocktemplateController.prometheus.serviceMonitor.labels the additional label of rocktemplateController serviceMonitor
      labels: {}

    prometheusRule:
      ## @param rocktemplateController.prometheus.prometheusRule.install install prometheusRule for template agent. This requires the prometheus CRDs to be available
      install: false

      ## @param rocktemplateController.prometheus.prometheusRule.namespace the prometheusRule namespace. Default to the namespace of helm instance
      namespace: ""

      ## @param rocktemplateController.prometheus.prometheusRule.annotations the additional annotations of rocktemplateController prometheusRule
      annotations: {}

      ## @param rocktemplateController.prometheus.prometheusRule.labels the additional label of rocktemplateController prometheusRule
      labels: {}

    grafanaDashboard:
      ## @param rocktemplateController.prometheus.grafanaDashboard.install install grafanaDashboard for template agent. This requires the prometheus CRDs to be available
      install: false

      ## @param rocktemplateController.prometheus.grafanaDashboard.namespace the grafanaDashboard namespace. Default to the namespace of helm instance
      namespace: ""

      ## @param rocktemplateController.prometheus.grafanaDashboard.annotations the additional annotations of rocktemplateController grafanaDashboard
      annotations: {}

      ## @param rocktemplateController.prometheus.grafanaDashboard.labels the additional label of rocktemplateController grafanaDashboard
      labels: {}

  debug:
    ## @param rocktemplateController.debug.logLevel the log level of template Controller [debug, info, warn, error, fatal, panic]
    logLevel: "info"

    ## @param rocktemplateController.debug.gopsPort the gops port of template Controller
    gopsPort: 5724

  ## TLS configuration for webhook
  tls:
    ## @param rocktemplateController.tls.method the method for generating TLS certificates. [ provided , certmanager , auto]
    ## - provided:     provide all certificates by helm options
    ## - certmanager:  This method use cert-manager to generate & rotate certificates.
    ## - auto:         Auto generate cert.
    method: auto

    ## @param rocktemplateController.tls.secretName the secret name for storing TLS certificates
    secretName: "template-controller-server-certs"

    ## for certmanager method
    certmanager:
      ## @param rocktemplateController.tls.certmanager.certValidityDuration generated certificates validity duration in days for 'certmanager' method
      certValidityDuration: 365

      ## @param rocktemplateController.tls.certmanager.issuerName issuer name of cert manager 'certmanager'. If not specified, a CA issuer will be created.
      issuerName: ""

      ## @param rocktemplateController.tls.certmanager.extraDnsNames extra DNS names added to certificate when it's auto generated
      extraDnsNames: []

      ## @param rocktemplateController.tls.certmanager.extraIPAddresses extra IP addresses added to certificate when it's auto generated
      extraIPAddresses: []

    ## for provided method
    provided:
      ## @param rocktemplateController.tls.provided.tlsCert encoded tls certificate for provided method
      ## @param rocktemplateController.tls.provided.tlsKey encoded tls key for provided method
      ## @param rocktemplateController.tls.provided.tlsCa encoded tls CA for provided method
      tlsCert: ""
      tlsKey: ""
      tlsCa: ""

    ## for auto method
    auto:
      ## @param rocktemplateController.tls.auto.caExpiration ca expiration for auto method
      # in day , default 200 years
      caExpiration: '73000'

      ## @param rocktemplateController.tls.auto.certExpiration server cert expiration for auto method
      # in day, default 200 years
      certExpiration: '73000'

      ## @param rocktemplateController.tls.auto.extraIpAddresses extra IP addresses of server certificate for auto method
      extraIpAddresses: []

      ## @param rocktemplateController.tls.auto.extraDnsNames extra DNS names of server cert for auto method
      extraDnsNames: []
