// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// KClusterListerExpansion allows custom methods to be added to
// KClusterLister.
type KClusterListerExpansion interface{}

// KClusterGroupListerExpansion allows custom methods to be added to
// KClusterGroupLister.
type KClusterGroupListerExpansion interface{}

// ServiceExportPolicyListerExpansion allows custom methods to be added to
// ServiceExportPolicyLister.
type ServiceExportPolicyListerExpansion interface{}
