// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KClusterLister helps list KClusters.
// All objects returned here must be treated as read-only.
type KClusterLister interface {
	// List lists all KClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.KCluster, err error)
	// Get retrieves the KCluster from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.KCluster, error)
	KClusterListerExpansion
}

// kClusterLister implements the KClusterLister interface.
type kClusterLister struct {
	indexer cache.Indexer
}

// NewKClusterLister returns a new KClusterLister.
func NewKClusterLister(indexer cache.Indexer) KClusterLister {
	return &kClusterLister{indexer: indexer}
}

// List lists all KClusters in the indexer.
func (s *kClusterLister) List(selector labels.Selector) (ret []*v1beta1.KCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.KCluster))
	})
	return ret, err
}

// Get retrieves the KCluster from the index for a given name.
func (s *kClusterLister) Get(name string) (*v1beta1.KCluster, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("kcluster"), name)
	}
	return obj.(*v1beta1.KCluster), nil
}
