// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ServiceExportPolicyLister helps list ServiceExportPolicies.
// All objects returned here must be treated as read-only.
type ServiceExportPolicyLister interface {
	// List lists all ServiceExportPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ServiceExportPolicy, err error)
	// Get retrieves the ServiceExportPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.ServiceExportPolicy, error)
	ServiceExportPolicyListerExpansion
}

// serviceExportPolicyLister implements the ServiceExportPolicyLister interface.
type serviceExportPolicyLister struct {
	indexer cache.Indexer
}

// NewServiceExportPolicyLister returns a new ServiceExportPolicyLister.
func NewServiceExportPolicyLister(indexer cache.Indexer) ServiceExportPolicyLister {
	return &serviceExportPolicyLister{indexer: indexer}
}

// List lists all ServiceExportPolicies in the indexer.
func (s *serviceExportPolicyLister) List(selector labels.Selector) (ret []*v1beta1.ServiceExportPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ServiceExportPolicy))
	})
	return ret, err
}

// Get retrieves the ServiceExportPolicy from the index for a given name.
func (s *serviceExportPolicyLister) Get(name string) (*v1beta1.ServiceExportPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("serviceexportpolicy"), name)
	}
	return obj.(*v1beta1.ServiceExportPolicy), nil
}
