// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1beta1"
	scheme "github.com/koffloader-io/koffloader/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KClusterGroupsGetter has a method to return a KClusterGroupInterface.
// A group's client should implement this interface.
type KClusterGroupsGetter interface {
	KClusterGroups() KClusterGroupInterface
}

// KClusterGroupInterface has methods to work with KClusterGroup resources.
type KClusterGroupInterface interface {
	Create(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.CreateOptions) (*v1beta1.KClusterGroup, error)
	Update(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.UpdateOptions) (*v1beta1.KClusterGroup, error)
	UpdateStatus(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.UpdateOptions) (*v1beta1.KClusterGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.KClusterGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.KClusterGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.KClusterGroup, err error)
	KClusterGroupExpansion
}

// kClusterGroups implements KClusterGroupInterface
type kClusterGroups struct {
	client rest.Interface
}

// newKClusterGroups returns a KClusterGroups
func newKClusterGroups(c *KoffloaderV1beta1Client) *kClusterGroups {
	return &kClusterGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the kClusterGroup, and returns the corresponding kClusterGroup object, and an error if there is any.
func (c *kClusterGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.KClusterGroup, err error) {
	result = &v1beta1.KClusterGroup{}
	err = c.client.Get().
		Resource("kclustergroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KClusterGroups that match those selectors.
func (c *kClusterGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.KClusterGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.KClusterGroupList{}
	err = c.client.Get().
		Resource("kclustergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kClusterGroups.
func (c *kClusterGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kclustergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kClusterGroup and creates it.  Returns the server's representation of the kClusterGroup, and an error, if there is any.
func (c *kClusterGroups) Create(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.CreateOptions) (result *v1beta1.KClusterGroup, err error) {
	result = &v1beta1.KClusterGroup{}
	err = c.client.Post().
		Resource("kclustergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kClusterGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kClusterGroup and updates it. Returns the server's representation of the kClusterGroup, and an error, if there is any.
func (c *kClusterGroups) Update(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.UpdateOptions) (result *v1beta1.KClusterGroup, err error) {
	result = &v1beta1.KClusterGroup{}
	err = c.client.Put().
		Resource("kclustergroups").
		Name(kClusterGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kClusterGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kClusterGroups) UpdateStatus(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.UpdateOptions) (result *v1beta1.KClusterGroup, err error) {
	result = &v1beta1.KClusterGroup{}
	err = c.client.Put().
		Resource("kclustergroups").
		Name(kClusterGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kClusterGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kClusterGroup and deletes it. Returns an error if one occurs.
func (c *kClusterGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kclustergroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kClusterGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kclustergroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kClusterGroup.
func (c *kClusterGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.KClusterGroup, err error) {
	result = &v1beta1.KClusterGroup{}
	err = c.client.Patch(pt).
		Resource("kclustergroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
