// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1beta1"
	scheme "github.com/koffloader-io/koffloader/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceExportPoliciesGetter has a method to return a ServiceExportPolicyInterface.
// A group's client should implement this interface.
type ServiceExportPoliciesGetter interface {
	ServiceExportPolicies() ServiceExportPolicyInterface
}

// ServiceExportPolicyInterface has methods to work with ServiceExportPolicy resources.
type ServiceExportPolicyInterface interface {
	Create(ctx context.Context, serviceExportPolicy *v1beta1.ServiceExportPolicy, opts v1.CreateOptions) (*v1beta1.ServiceExportPolicy, error)
	Update(ctx context.Context, serviceExportPolicy *v1beta1.ServiceExportPolicy, opts v1.UpdateOptions) (*v1beta1.ServiceExportPolicy, error)
	UpdateStatus(ctx context.Context, serviceExportPolicy *v1beta1.ServiceExportPolicy, opts v1.UpdateOptions) (*v1beta1.ServiceExportPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ServiceExportPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ServiceExportPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ServiceExportPolicy, err error)
	ServiceExportPolicyExpansion
}

// serviceExportPolicies implements ServiceExportPolicyInterface
type serviceExportPolicies struct {
	client rest.Interface
}

// newServiceExportPolicies returns a ServiceExportPolicies
func newServiceExportPolicies(c *KoffloaderV1beta1Client) *serviceExportPolicies {
	return &serviceExportPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the serviceExportPolicy, and returns the corresponding serviceExportPolicy object, and an error if there is any.
func (c *serviceExportPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ServiceExportPolicy, err error) {
	result = &v1beta1.ServiceExportPolicy{}
	err = c.client.Get().
		Resource("serviceexportpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceExportPolicies that match those selectors.
func (c *serviceExportPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ServiceExportPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ServiceExportPolicyList{}
	err = c.client.Get().
		Resource("serviceexportpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceExportPolicies.
func (c *serviceExportPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("serviceexportpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a serviceExportPolicy and creates it.  Returns the server's representation of the serviceExportPolicy, and an error, if there is any.
func (c *serviceExportPolicies) Create(ctx context.Context, serviceExportPolicy *v1beta1.ServiceExportPolicy, opts v1.CreateOptions) (result *v1beta1.ServiceExportPolicy, err error) {
	result = &v1beta1.ServiceExportPolicy{}
	err = c.client.Post().
		Resource("serviceexportpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceExportPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a serviceExportPolicy and updates it. Returns the server's representation of the serviceExportPolicy, and an error, if there is any.
func (c *serviceExportPolicies) Update(ctx context.Context, serviceExportPolicy *v1beta1.ServiceExportPolicy, opts v1.UpdateOptions) (result *v1beta1.ServiceExportPolicy, err error) {
	result = &v1beta1.ServiceExportPolicy{}
	err = c.client.Put().
		Resource("serviceexportpolicies").
		Name(serviceExportPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceExportPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *serviceExportPolicies) UpdateStatus(ctx context.Context, serviceExportPolicy *v1beta1.ServiceExportPolicy, opts v1.UpdateOptions) (result *v1beta1.ServiceExportPolicy, err error) {
	result = &v1beta1.ServiceExportPolicy{}
	err = c.client.Put().
		Resource("serviceexportpolicies").
		Name(serviceExportPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceExportPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the serviceExportPolicy and deletes it. Returns an error if one occurs.
func (c *serviceExportPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("serviceexportpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceExportPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("serviceexportpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched serviceExportPolicy.
func (c *serviceExportPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ServiceExportPolicy, err error) {
	result = &v1beta1.ServiceExportPolicy{}
	err = c.client.Patch(pt).
		Resource("serviceexportpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
