// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1"
	scheme "github.com/koffloader-io/koffloader/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KclustersGetter has a method to return a KclusterInterface.
// A group's client should implement this interface.
type KclustersGetter interface {
	Kclusters() KclusterInterface
}

// KclusterInterface has methods to work with Kcluster resources.
type KclusterInterface interface {
	Create(ctx context.Context, kcluster *v1.Kcluster, opts metav1.CreateOptions) (*v1.Kcluster, error)
	Update(ctx context.Context, kcluster *v1.Kcluster, opts metav1.UpdateOptions) (*v1.Kcluster, error)
	UpdateStatus(ctx context.Context, kcluster *v1.Kcluster, opts metav1.UpdateOptions) (*v1.Kcluster, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Kcluster, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.KclusterList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Kcluster, err error)
	KclusterExpansion
}

// kclusters implements KclusterInterface
type kclusters struct {
	client rest.Interface
}

// newKclusters returns a Kclusters
func newKclusters(c *koffloaderV1Client) *kclusters {
	return &kclusters{
		client: c.RESTClient(),
	}
}

// Get takes name of the kcluster, and returns the corresponding kcluster object, and an error if there is any.
func (c *kclusters) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Kcluster, err error) {
	result = &v1.Kcluster{}
	err = c.client.Get().
		Resource("kclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kclusters that match those selectors.
func (c *kclusters) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KclusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KclusterList{}
	err = c.client.Get().
		Resource("kclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kclusters.
func (c *kclusters) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kcluster and creates it.  Returns the server's representation of the kcluster, and an error, if there is any.
func (c *kclusters) Create(ctx context.Context, kcluster *v1.Kcluster, opts metav1.CreateOptions) (result *v1.Kcluster, err error) {
	result = &v1.Kcluster{}
	err = c.client.Post().
		Resource("kclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kcluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kcluster and updates it. Returns the server's representation of the kcluster, and an error, if there is any.
func (c *kclusters) Update(ctx context.Context, kcluster *v1.Kcluster, opts metav1.UpdateOptions) (result *v1.Kcluster, err error) {
	result = &v1.Kcluster{}
	err = c.client.Put().
		Resource("kclusters").
		Name(kcluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kcluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kclusters) UpdateStatus(ctx context.Context, kcluster *v1.Kcluster, opts metav1.UpdateOptions) (result *v1.Kcluster, err error) {
	result = &v1.Kcluster{}
	err = c.client.Put().
		Resource("kclusters").
		Name(kcluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kcluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kcluster and deletes it. Returns an error if one occurs.
func (c *kclusters) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kclusters) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kcluster.
func (c *kclusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Kcluster, err error) {
	result = &v1.Kcluster{}
	err = c.client.Patch(pt).
		Resource("kclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
