// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKClusterGroups implements KClusterGroupInterface
type FakeKClusterGroups struct {
	Fake *FakeKoffloaderV1beta1
}

var kclustergroupsResource = schema.GroupVersionResource{Group: "koffloader.koffloader.io", Version: "v1beta1", Resource: "kclustergroups"}

var kclustergroupsKind = schema.GroupVersionKind{Group: "koffloader.koffloader.io", Version: "v1beta1", Kind: "KClusterGroup"}

// Get takes name of the kClusterGroup, and returns the corresponding kClusterGroup object, and an error if there is any.
func (c *FakeKClusterGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.KClusterGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kclustergroupsResource, name), &v1beta1.KClusterGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KClusterGroup), err
}

// List takes label and field selectors, and returns the list of KClusterGroups that match those selectors.
func (c *FakeKClusterGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.KClusterGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kclustergroupsResource, kclustergroupsKind, opts), &v1beta1.KClusterGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.KClusterGroupList{ListMeta: obj.(*v1beta1.KClusterGroupList).ListMeta}
	for _, item := range obj.(*v1beta1.KClusterGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kClusterGroups.
func (c *FakeKClusterGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kclustergroupsResource, opts))
}

// Create takes the representation of a kClusterGroup and creates it.  Returns the server's representation of the kClusterGroup, and an error, if there is any.
func (c *FakeKClusterGroups) Create(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.CreateOptions) (result *v1beta1.KClusterGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kclustergroupsResource, kClusterGroup), &v1beta1.KClusterGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KClusterGroup), err
}

// Update takes the representation of a kClusterGroup and updates it. Returns the server's representation of the kClusterGroup, and an error, if there is any.
func (c *FakeKClusterGroups) Update(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.UpdateOptions) (result *v1beta1.KClusterGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kclustergroupsResource, kClusterGroup), &v1beta1.KClusterGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KClusterGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKClusterGroups) UpdateStatus(ctx context.Context, kClusterGroup *v1beta1.KClusterGroup, opts v1.UpdateOptions) (*v1beta1.KClusterGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kclustergroupsResource, "status", kClusterGroup), &v1beta1.KClusterGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KClusterGroup), err
}

// Delete takes name of the kClusterGroup and deletes it. Returns an error if one occurs.
func (c *FakeKClusterGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(kclustergroupsResource, name, opts), &v1beta1.KClusterGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKClusterGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kclustergroupsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.KClusterGroupList{})
	return err
}

// Patch applies the patch and returns the patched kClusterGroup.
func (c *FakeKClusterGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.KClusterGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kclustergroupsResource, name, pt, data, subresources...), &v1beta1.KClusterGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KClusterGroup), err
}
