// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/koffloader-io/koffloader/pkg/k8s/client/clientset/versioned/typed/koffloader.koffloader.io/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKoffloaderV1beta1 struct {
	*testing.Fake
}

func (c *FakeKoffloaderV1beta1) KClusters() v1beta1.KClusterInterface {
	return &FakeKClusters{c}
}

func (c *FakeKoffloaderV1beta1) KClusterGroups() v1beta1.KClusterGroupInterface {
	return &FakeKClusterGroups{c}
}

func (c *FakeKoffloaderV1beta1) ServiceExportPolicies() v1beta1.ServiceExportPolicyInterface {
	return &FakeServiceExportPolicies{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKoffloaderV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
