// Copyright 2024 Authors of koffloader-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	koffloaderkoffloaderiov1 "github.com/koffloader-io/koffloader/pkg/k8s/apis/koffloader.koffloader.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKclusters implements KclusterInterface
type FakeKclusters struct {
	Fake *FakeKoffloaderV1
}

var kclustersResource = schema.GroupVersionResource{Group: "koffloader.koffloader.io", Version: "v1", Resource: "kclusters"}

var kclustersKind = schema.GroupVersionKind{Group: "koffloader.koffloader.io", Version: "v1", Kind: "Kcluster"}

// Get takes name of the kcluster, and returns the corresponding kcluster object, and an error if there is any.
func (c *FakeKclusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *koffloaderkoffloaderiov1.Kcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kclustersResource, name), &koffloaderkoffloaderiov1.Kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderkoffloaderiov1.Kcluster), err
}

// List takes label and field selectors, and returns the list of Kclusters that match those selectors.
func (c *FakeKclusters) List(ctx context.Context, opts v1.ListOptions) (result *koffloaderkoffloaderiov1.KclusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kclustersResource, kclustersKind, opts), &koffloaderkoffloaderiov1.KclusterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &koffloaderkoffloaderiov1.KclusterList{ListMeta: obj.(*koffloaderkoffloaderiov1.KclusterList).ListMeta}
	for _, item := range obj.(*koffloaderkoffloaderiov1.KclusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kclusters.
func (c *FakeKclusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kclustersResource, opts))
}

// Create takes the representation of a kcluster and creates it.  Returns the server's representation of the kcluster, and an error, if there is any.
func (c *FakeKclusters) Create(ctx context.Context, kcluster *koffloaderkoffloaderiov1.Kcluster, opts v1.CreateOptions) (result *koffloaderkoffloaderiov1.Kcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kclustersResource, kcluster), &koffloaderkoffloaderiov1.Kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderkoffloaderiov1.Kcluster), err
}

// Update takes the representation of a kcluster and updates it. Returns the server's representation of the kcluster, and an error, if there is any.
func (c *FakeKclusters) Update(ctx context.Context, kcluster *koffloaderkoffloaderiov1.Kcluster, opts v1.UpdateOptions) (result *koffloaderkoffloaderiov1.Kcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kclustersResource, kcluster), &koffloaderkoffloaderiov1.Kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderkoffloaderiov1.Kcluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKclusters) UpdateStatus(ctx context.Context, kcluster *koffloaderkoffloaderiov1.Kcluster, opts v1.UpdateOptions) (*koffloaderkoffloaderiov1.Kcluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kclustersResource, "status", kcluster), &koffloaderkoffloaderiov1.Kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderkoffloaderiov1.Kcluster), err
}

// Delete takes name of the kcluster and deletes it. Returns an error if one occurs.
func (c *FakeKclusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(kclustersResource, name, opts), &koffloaderkoffloaderiov1.Kcluster{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKclusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kclustersResource, listOpts)

	_, err := c.Fake.Invokes(action, &koffloaderkoffloaderiov1.KclusterList{})
	return err
}

// Patch applies the patch and returns the patched kcluster.
func (c *FakeKclusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *koffloaderkoffloaderiov1.Kcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kclustersResource, name, pt, data, subresources...), &koffloaderkoffloaderiov1.Kcluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*koffloaderkoffloaderiov1.Kcluster), err
}
